"""
    ChatApp

    This is a documentation of my ChatApp API.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.messages_api import MessagesApi  # noqa: E501


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_receive(self):
        """Test case for receive

        Receive messages for conversation  # noqa: E501
        """
        pass

    def test_send(self):
        """Test case for send

        Send a message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
