"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.jsonapi_error409 import JsonapiError409


class TestJsonapiError409(unittest.TestCase):
    """JsonapiError409 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonapiError409(self):
        """Test JsonapiError409"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JsonapiError409()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
