"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.memberships_api import MembershipsApi  # noqa: E501


class TestMembershipsApi(unittest.TestCase):
    """MembershipsApi unit test stubs"""

    def setUp(self):
        self.api = MembershipsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_membership0(self):
        """Test case for create_membership0

        Create Membership  # noqa: E501
        """
        pass

    def test_delete_membershipfrom_memberships0(self):
        """Test case for delete_membershipfrom_memberships0

        Delete Membership from Memberships  # noqa: E501
        """
        pass

    def test_retrieve_membershipinstance0(self):
        """Test case for retrieve_membershipinstance0

        Retrieve Membership instance  # noqa: E501
        """
        pass

    def test_retrieveacollectionof_membershipobjects0(self):
        """Test case for retrieveacollectionof_membershipobjects0

        Retrieve a collection of Membership objects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
