"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.jsonapi_error500 import JsonapiError500


class TestJsonapiError500(unittest.TestCase):
    """JsonapiError500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonapiError500(self):
        """Test JsonapiError500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JsonapiError500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
