"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.conversation_coll import ConversationColl


class TestConversationColl(unittest.TestCase):
    """ConversationColl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversationColl(self):
        """Test ConversationColl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConversationColl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
