"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.conversation_messages_rel_coll import ConversationMessagesRelColl


class TestConversationMessagesRelColl(unittest.TestCase):
    """ConversationMessagesRelColl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversationMessagesRelColl(self):
        """Test ConversationMessagesRelColl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConversationMessagesRelColl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
