version: "3.1"

services:
  pwr:
    restart: always 
    container_name: serwer
    build: ./
    ports: 
      - "5000:5000"
    environment: 
      DB_HOST: database
      DB_USER: root
      DB_PASS: pass
      DB_NAME: serwer_database

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULTS_SERVER: database
    ports:
    - 8080:8080

  autoheal:
      restart: always
      image: willfarrell/autoheal
      environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
