"""
    Weatherbit.io - Swagger UI Weather API documentation

    This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class HistoryDayObj(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'datetime': (str,),  # noqa: E501
            'ts': (int,),  # noqa: E501
            'slp': (float,),  # noqa: E501
            'pres': (float,),  # noqa: E501
            'rh': (int,),  # noqa: E501
            'dewpt': (float,),  # noqa: E501
            'temp': (float,),  # noqa: E501
            'max_temp': (float,),  # noqa: E501
            'max_temp_ts': (float,),  # noqa: E501
            'min_temp': (float,),  # noqa: E501
            'min_temp_ts': (float,),  # noqa: E501
            'wind_spd': (float,),  # noqa: E501
            'wind_dir': (int,),  # noqa: E501
            'wind_gust_spd': (float,),  # noqa: E501
            'max_wind_spd': (float,),  # noqa: E501
            'max_wind_dir': (int,),  # noqa: E501
            'max_wind_spd_ts': (float,),  # noqa: E501
            'ghi': (int,),  # noqa: E501
            't_ghi': (int,),  # noqa: E501
            'dni': (int,),  # noqa: E501
            't_dni': (int,),  # noqa: E501
            'dhi': (int,),  # noqa: E501
            't_dhi': (int,),  # noqa: E501
            'max_uv': (float,),  # noqa: E501
            'precip': (float,),  # noqa: E501
            'precip_gpm': (float,),  # noqa: E501
            'snow': (float,),  # noqa: E501
            'snow_depth': (float,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'datetime': 'datetime',  # noqa: E501
        'ts': 'ts',  # noqa: E501
        'slp': 'slp',  # noqa: E501
        'pres': 'pres',  # noqa: E501
        'rh': 'rh',  # noqa: E501
        'dewpt': 'dewpt',  # noqa: E501
        'temp': 'temp',  # noqa: E501
        'max_temp': 'max_temp',  # noqa: E501
        'max_temp_ts': 'max_temp_ts',  # noqa: E501
        'min_temp': 'min_temp',  # noqa: E501
        'min_temp_ts': 'min_temp_ts',  # noqa: E501
        'wind_spd': 'wind_spd',  # noqa: E501
        'wind_dir': 'wind_dir',  # noqa: E501
        'wind_gust_spd': 'wind_gust_spd',  # noqa: E501
        'max_wind_spd': 'max_wind_spd',  # noqa: E501
        'max_wind_dir': 'max_wind_dir',  # noqa: E501
        'max_wind_spd_ts': 'max_wind_spd_ts',  # noqa: E501
        'ghi': 'ghi',  # noqa: E501
        't_ghi': 't_ghi',  # noqa: E501
        'dni': 'dni',  # noqa: E501
        't_dni': 't_dni',  # noqa: E501
        'dhi': 'dhi',  # noqa: E501
        't_dhi': 't_dhi',  # noqa: E501
        'max_uv': 'max_uv',  # noqa: E501
        'precip': 'precip',  # noqa: E501
        'precip_gpm': 'precip_gpm',  # noqa: E501
        'snow': 'snow',  # noqa: E501
        'snow_depth': 'snow_depth',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """HistoryDayObj - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            datetime (str): Date in format \"YYYY-MM-DD\". All datetime is in (UTC). [optional]  # noqa: E501
            ts (int): Unix timestamp of datetime (Midnight UTC). [optional]  # noqa: E501
            slp (float): Average sea level pressure (mb). [optional]  # noqa: E501
            pres (float): Average pressure (mb). [optional]  # noqa: E501
            rh (int): Average relative humidity as a percentage (%). [optional]  # noqa: E501
            dewpt (float): Average dewpoint - Default (C). [optional]  # noqa: E501
            temp (float): Average temperature - Default (C). [optional]  # noqa: E501
            max_temp (float): Max temperature - Default (C). [optional]  # noqa: E501
            max_temp_ts (float): Time of max memperature - Unix Timestamp. [optional]  # noqa: E501
            min_temp (float): Min temperature - Default (C). [optional]  # noqa: E501
            min_temp_ts (float): Time of max temperature - unix timestamp. [optional]  # noqa: E501
            wind_spd (float): Average wind speed - default (m/s). [optional]  # noqa: E501
            wind_dir (int): Average wind direction (degrees). [optional]  # noqa: E501
            wind_gust_spd (float): Wind gust speed - default (m/s). [optional]  # noqa: E501
            max_wind_spd (float): Max 2min Wind Speed - default (m/s). [optional]  # noqa: E501
            max_wind_dir (int): Direction of wind at time of max 2min wind (degrees). [optional]  # noqa: E501
            max_wind_spd_ts (float): Time of max 2min wind - unix timestamp. [optional]  # noqa: E501
            ghi (int): Average hourly global horizontal solar irradiance (W/m^2). [optional]  # noqa: E501
            t_ghi (int): Total global horizontal solar irradiance (W/m^2). [optional]  # noqa: E501
            dni (int): Average direct normal solar irradiance (W/m^2). [optional]  # noqa: E501
            t_dni (int): Total direct normal solar irradiance (W/m^2). [optional]  # noqa: E501
            dhi (int): Average hourly diffuse horizontal solar irradiance (W/m^2). [optional]  # noqa: E501
            t_dhi (int): Total diffuse horizontal solar irradiance (W/m^2). [optional]  # noqa: E501
            max_uv (float): Max UV Index (1-11+). [optional]  # noqa: E501
            precip (float): Liquid equivalent precipitation - default (mm). [optional]  # noqa: E501
            precip_gpm (float): Satellite estimated liquid equivalent precipitation - default (mm). [optional]  # noqa: E501
            snow (float): Snowfall - default (mm). [optional]  # noqa: E501
            snow_depth (float): Snow Depth - default (mm). [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
