"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.message_coll1 import MessageColl1


class TestMessageColl1(unittest.TestCase):
    """MessageColl1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageColl1(self):
        """Test MessageColl1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageColl1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
