"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user_inst1 import UserInst1


class TestUserInst1(unittest.TestCase):
    """UserInst1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInst1(self):
        """Test UserInst1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserInst1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
