"""
    ChatApp

    This is a documentation of my ChatApp API.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user(self):
        """Test case for get_user

        Get user info  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        List logged users  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        Login user  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        Logout user  # noqa: E501
        """
        pass

    def test_register(self):
        """Test case for register

        Register user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
