# flake8: noqa

"""
    Weatherbit.io - Swagger UI Weather API documentation

    This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from ..openapi_client.api_client import ApiClient

# import Configuration
from ..openapi_client.configuration import Configuration

# import exceptions
from ..openapi_client.exceptions import OpenApiException
from ..openapi_client.exceptions import ApiAttributeError
from ..openapi_client.exceptions import ApiTypeError
from ..openapi_client.exceptions import ApiValueError
from ..openapi_client.exceptions import ApiKeyError
from ..openapi_client.exceptions import ApiException
