"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.membership_inst1 import MembershipInst1


class TestMembershipInst1(unittest.TestCase):
    """MembershipInst1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMembershipInst1(self):
        """Test MembershipInst1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MembershipInst1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
