"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.conversation_coll1 import ConversationColl1


class TestConversationColl1(unittest.TestCase):
    """ConversationColl1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversationColl1(self):
        """Test ConversationColl1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConversationColl1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
