"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ...openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from ...openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from ...openapi_client.model.conversation_coll1 import ConversationColl1
from ...openapi_client.model.conversation_inst1 import ConversationInst
from ...openapi_client.model.conversation_memberships_rel_coll import ConversationMembershipsRelColl
from ...openapi_client.model.conversation_messages_rel_coll import ConversationMessagesRelColl
from ...openapi_client.model.conversation_users_rel_coll import ConversationUsersRelColl
from ...openapi_client.model.jsonapi_error400 import JsonapiError400
from ...openapi_client.model.jsonapi_error403 import JsonapiError403
from ...openapi_client.model.jsonapi_error404 import JsonapiError404
from ...openapi_client.model.jsonapi_error405 import JsonapiError405
from ...openapi_client.model.jsonapi_error409 import JsonapiError409
from ...openapi_client.model.jsonapi_error500 import JsonapiError500


class ConversationsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __create_conversation0(
            self,
            post_body,
            content_type="application/vnd.api+json",
            **kwargs
        ):
            """Create Conversation  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.create_conversation(post_body, content_type="application/vnd.api+json", async_req=True)
            >>> result = thread.get()

            Args:
                post_body (ConversationInst): Conversation attributes
                content_type (str): defaults to "application/vnd.api+json", must be one of ["application/vnd.api+json"]

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationInst1
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['content_type'] = \
                content_type
            kwargs['post_body'] = \
                post_body
            return self.call_with_http_info(**kwargs)

        self.create_conversation = _Endpoint(
            settings={
                'response_type': (ConversationInst,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/',
                'operation_id': 'create_conversation0',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'content_type',
                    'post_body',
                ],
                'required': [
                    'content_type',
                    'post_body',
                ],
                'nullable': [
                ],
                'enum': [
                    'content_type',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('content_type',): {

                        "VND.API+JSON": "application/vnd.api+json",
                        "JSON": "application/json"
                    },
                },
                'openapi_types': {
                    'content_type':
                        (str,),
                    'post_body':
                        (ConversationInst,),
                },
                'attribute_map': {
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'content_type': 'header',
                    'post_body': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/vnd.api+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__create_conversation0
        )

        def __delete_conversationfrom_conversations0(
            self,
            conversation_id="jsonapi_id_string",
            content_type="application/vnd.api+json",
            **kwargs
        ):
            """Delete Conversation from Conversations  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_conversationfrom_conversations0(conversation_id="jsonapi_id_string", content_type="application/vnd.api+json", async_req=True)
            >>> result = thread.get()

            Args:
                conversation_id (str): defaults to "jsonapi_id_string", must be one of ["jsonapi_id_string"]
                content_type (str): defaults to "application/vnd.api+json", must be one of ["application/vnd.api+json"]

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationInst1
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['conversation_id'] = \
                conversation_id
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.delete_conversationfrom_conversations0 = _Endpoint(
            settings={
                'response_type': (ConversationInst,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/{ConversationId}/',
                'operation_id': 'delete_conversationfrom_conversations0',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'conversation_id',
                    'content_type',
                ],
                'required': [
                    'conversation_id',
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                    'content_type',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('content_type',): {

                        "VND.API+JSON": "application/vnd.api+json",
                        "JSON": "application/json"
                    },
                },
                'openapi_types': {
                    'conversation_id':
                        (str,),
                    'content_type':
                        (str,),
                },
                'attribute_map': {
                    'conversation_id': 'ConversationId',
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'conversation_id': 'path',
                    'content_type': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/vnd.api+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_conversationfrom_conversations0
        )

        def __retrieve_conversationinstance0(
            self,
            conversation_id="jsonapi_id_string",
            content_type="application/vnd.api+json",
            **kwargs
        ):
            """Retrieve Conversation instance  # noqa: E501

            Retrieve Conversation from Conversations  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_conversation(conversation_id="jsonapi_id_string", content_type="application/vnd.api+json", async_req=True)
            >>> result = thread.get()

            Args:
                conversation_id (str): defaults to "jsonapi_id_string", must be one of ["jsonapi_id_string"]
                content_type (str): defaults to "application/vnd.api+json", must be one of ["application/vnd.api+json"]

            Keyword Args:
                include (str): Conversation relationships to include (csv). [optional] if omitted the server will use the default value of "messages,memberships,users"
                fields_conversation (str): Conversation fields to include (csv). [optional] if omitted the server will use the default value of "name"
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationInst1
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['conversation_id'] = \
                conversation_id
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.get_conversation = _Endpoint(
            settings={
                'response_type': (ConversationInst,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/{ConversationId}/',
                'operation_id': 'retrieve_conversationinstance0',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'conversation_id',
                    'content_type',
                    'include',
                    'fields_conversation',
                ],
                'required': [
                    'conversation_id',
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                    'content_type',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('content_type',): {

                        "VND.API+JSON": "application/vnd.api+json",
                        "JSON": "application/json"
                    },
                },
                'openapi_types': {
                    'conversation_id':
                        (str,),
                    'content_type':
                        (str,),
                    'include':
                        (str,),
                    'fields_conversation':
                        (str,),
                },
                'attribute_map': {
                    'conversation_id': 'ConversationId',
                    'content_type': 'Content-Type',
                    'include': 'include',
                    'fields_conversation': 'fields[Conversation]',
                },
                'location_map': {
                    'conversation_id': 'path',
                    'content_type': 'header',
                    'include': 'query',
                    'fields_conversation': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/vnd.api+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__retrieve_conversationinstance0
        )

        def __retrieve_membershipfrommemberships1(
            self,
            conversation_id="jsonapi_id_string",
            **kwargs
        ):
            """Retrieve Membership from memberships  # noqa: E501

            Retrieve Membership items from the Conversation memberships \"to-many\" relationship  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_memberships(conversation_id="jsonapi_id_string", async_req=True)
            >>> result = thread.get()

            Args:
                conversation_id (str): Conversation item. defaults to "jsonapi_id_string", must be one of ["jsonapi_id_string"]

            Keyword Args:
                include (str): Membership relationships to include (csv). [optional]
                fields_membership (str): Membership fields to include (csv). [optional] if omitted the server will use the default value of "user_id,conversation_id,last_download,last_read"
                page_offset (int): Page offset. [optional] if omitted the server will use the default value of 0
                page_limit (int): Max number of items. [optional] if omitted the server will use the default value of 10
                sort (str): Sort order. [optional] if omitted the server will use the default value of "user_id,conversation_id,last_download,last_read,id"
                filter_user_id (str): user_id attribute filter (csv). [optional]
                filter_conversation_id (str): conversation_id attribute filter (csv). [optional]
                filter_last_download (str): last_download attribute filter (csv). [optional]
                filter_last_read (str): last_read attribute filter (csv). [optional]
                filter_id (str): id attribute filter (csv). [optional]
                filter (str): Custom Membership filter. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationMembershipsRelColl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['conversation_id'] = \
                conversation_id
            return self.call_with_http_info(**kwargs)

        self.get_memberships = _Endpoint(
            settings={
                'response_type': (ConversationMembershipsRelColl,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/{ConversationId}/memberships',
                'operation_id': 'retrieve_membershipfrommemberships1',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'conversation_id',
                    'include',
                    'fields_membership',
                    'page_offset',
                    'page_limit',
                    'sort',
                    'filter_user_id',
                    'filter_conversation_id',
                    'filter_last_download',
                    'filter_last_read',
                    'filter_id',
                    'filter',
                ],
                'required': [
                    'conversation_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'conversation_id':
                        (str,),
                    'include':
                        (str,),
                    'fields_membership':
                        (str,),
                    'page_offset':
                        (int,),
                    'page_limit':
                        (int,),
                    'sort':
                        (str,),
                    'filter_user_id':
                        (str,),
                    'filter_conversation_id':
                        (str,),
                    'filter_last_download':
                        (str,),
                    'filter_last_read':
                        (str,),
                    'filter_id':
                        (str,),
                    'filter':
                        (str,),
                },
                'attribute_map': {
                    'conversation_id': 'ConversationId',
                    'include': 'include',
                    'fields_membership': 'fields[Membership]',
                    'page_offset': 'page[offset]',
                    'page_limit': 'page[limit]',
                    'sort': 'sort',
                    'filter_user_id': 'filter[user_id]',
                    'filter_conversation_id': 'filter[conversation_id]',
                    'filter_last_download': 'filter[last_download]',
                    'filter_last_read': 'filter[last_read]',
                    'filter_id': 'filter[id]',
                    'filter': 'filter',
                },
                'location_map': {
                    'conversation_id': 'path',
                    'include': 'query',
                    'fields_membership': 'query',
                    'page_offset': 'query',
                    'page_limit': 'query',
                    'sort': 'query',
                    'filter_user_id': 'query',
                    'filter_conversation_id': 'query',
                    'filter_last_download': 'query',
                    'filter_last_read': 'query',
                    'filter_id': 'query',
                    'filter': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__retrieve_membershipfrommemberships1
        )

        def __retrieve_messagefrommessages0(
            self,
            conversation_id="jsonapi_id_string",
            **kwargs
        ):
            """Retrieve Message from messages  # noqa: E501

            Retrieve Message items from the Conversation messages \"to-many\" relationship  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_messages(conversation_id="jsonapi_id_string", async_req=True)
            >>> result = thread.get()

            Args:
                conversation_id (str): Conversation item. defaults to "jsonapi_id_string", must be one of ["jsonapi_id_string"]

            Keyword Args:
                include (str): Message relationships to include (csv). [optional]
                fields_message (str): Message fields to include (csv). [optional] if omitted the server will use the default value of "content,send_date,user_id,conversation_id"
                page_offset (int): Page offset. [optional] if omitted the server will use the default value of 0
                page_limit (int): Max number of items. [optional] if omitted the server will use the default value of 10
                sort (str): Sort order. [optional] if omitted the server will use the default value of "content,send_date,user_id,conversation_id,id"
                filter_content (str): content attribute filter (csv). [optional]
                filter_send_date (str): send_date attribute filter (csv). [optional]
                filter_user_id (str): user_id attribute filter (csv). [optional]
                filter_conversation_id (str): conversation_id attribute filter (csv). [optional]
                filter_id (str): id attribute filter (csv). [optional]
                filter (str): Custom Message filter. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationMessagesRelColl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['conversation_id'] = \
                conversation_id
            return self.call_with_http_info(**kwargs)

        self.get_messages = _Endpoint(
            settings={
                'response_type': (ConversationMessagesRelColl,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/{ConversationId}/messages',
                'operation_id': 'get_messages',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'conversation_id',
                    'include',
                    'fields_message',
                    'page_offset',
                    'page_limit',
                    'sort',
                    'filter_content',
                    'filter_send_date',
                    'filter_user_id',
                    'filter_conversation_id',
                    'filter_id',
                    'filter',
                ],
                'required': [
                    'conversation_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'conversation_id':
                        (str,),
                    'include':
                        (str,),
                    'fields_message':
                        (str,),
                    'page_offset':
                        (int,),
                    'page_limit':
                        (int,),
                    'sort':
                        (str,),
                    'filter_content':
                        (str,),
                    'filter_send_date':
                        (str,),
                    'filter_user_id':
                        (str,),
                    'filter_conversation_id':
                        (str,),
                    'filter_id':
                        (str,),
                    'filter':
                        (str,),
                },
                'attribute_map': {
                    'conversation_id': 'ConversationId',
                    'include': 'include',
                    'fields_message': 'fields[Message]',
                    'page_offset': 'page[offset]',
                    'page_limit': 'page[limit]',
                    'sort': 'sort',
                    'filter_content': 'filter[content]',
                    'filter_send_date': 'filter[send_date]',
                    'filter_user_id': 'filter[user_id]',
                    'filter_conversation_id': 'filter[conversation_id]',
                    'filter_id': 'filter[id]',
                    'filter': 'filter',
                },
                'location_map': {
                    'conversation_id': 'path',
                    'include': 'query',
                    'fields_message': 'query',
                    'page_offset': 'query',
                    'page_limit': 'query',
                    'sort': 'query',
                    'filter_content': 'query',
                    'filter_send_date': 'query',
                    'filter_user_id': 'query',
                    'filter_conversation_id': 'query',
                    'filter_id': 'query',
                    'filter': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__retrieve_messagefrommessages0
        )

        def __retrieve_userfromusers0(
            self,
            conversation_id="jsonapi_id_string",
            **kwargs
        ):
            """Retrieve User from users  # noqa: E501

            Retrieve User items from the Conversation users \"to-many\" relationship  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_users(conversation_id="jsonapi_id_string", async_req=True)
            >>> result = thread.get()

            Args:
                conversation_id (str): Conversation item. defaults to "jsonapi_id_string", must be one of ["jsonapi_id_string"]

            Keyword Args:
                include (str): User relationships to include (csv). [optional] if omitted the server will use the default value of "memberships,conversations"
                fields_user (str): User fields to include (csv). [optional] if omitted the server will use the default value of "last_active,name,password"
                page_offset (int): Page offset. [optional] if omitted the server will use the default value of 0
                page_limit (int): Max number of items. [optional] if omitted the server will use the default value of 10
                sort (str): Sort order. [optional] if omitted the server will use the default value of "last_active,name,password,id"
                filter_last_active (str): last_active attribute filter (csv). [optional]
                filter_name (str): name attribute filter (csv). [optional]
                filter_password (str): password attribute filter (csv). [optional]
                filter_id (str): id attribute filter (csv). [optional]
                filter (str): Custom User filter. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationUsersRelColl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['conversation_id'] = \
                conversation_id
            return self.call_with_http_info(**kwargs)

        self.get_users = _Endpoint(
            settings={
                'response_type': (ConversationUsersRelColl,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/{ConversationId}/users',
                'operation_id': 'retrieve_userfromusers0',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'conversation_id',
                    'include',
                    'fields_user',
                    'page_offset',
                    'page_limit',
                    'sort',
                    'filter_last_active',
                    'filter_name',
                    'filter_password',
                    'filter_id',
                    'filter',
                ],
                'required': [
                    'conversation_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'conversation_id':
                        (str,),
                    'include':
                        (str,),
                    'fields_user':
                        (str,),
                    'page_offset':
                        (int,),
                    'page_limit':
                        (int,),
                    'sort':
                        (str,),
                    'filter_last_active':
                        (str,),
                    'filter_name':
                        (str,),
                    'filter_password':
                        (str,),
                    'filter_id':
                        (str,),
                    'filter':
                        (str,),
                },
                'attribute_map': {
                    'conversation_id': 'ConversationId',
                    'include': 'include',
                    'fields_user': 'fields[User]',
                    'page_offset': 'page[offset]',
                    'page_limit': 'page[limit]',
                    'sort': 'sort',
                    'filter_last_active': 'filter[last_active]',
                    'filter_name': 'filter[name]',
                    'filter_password': 'filter[password]',
                    'filter_id': 'filter[id]',
                    'filter': 'filter',
                },
                'location_map': {
                    'conversation_id': 'path',
                    'include': 'query',
                    'fields_user': 'query',
                    'page_offset': 'query',
                    'page_limit': 'query',
                    'sort': 'query',
                    'filter_last_active': 'query',
                    'filter_name': 'query',
                    'filter_password': 'query',
                    'filter_id': 'query',
                    'filter': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__retrieve_userfromusers0
        )

        def __retrieveacollectionof_conversationobjects0(
            self,
            content_type="application/vnd.api+json",
            **kwargs
        ):
            """Retrieve a collection of Conversation objects  # noqa: E501

            Retrieve Conversation from Conversations  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_conversations(content_type="application/vnd.api+json", async_req=True)
            >>> result = thread.get()

            Args:
                content_type (str): defaults to "application/vnd.api+json", must be one of ["application/vnd.api+json"]

            Keyword Args:
                include (str): Conversation relationships to include (csv). [optional] if omitted the server will use the default value of "messages,memberships,users"
                fields_conversation (str): Conversation fields to include (csv). [optional] if omitted the server will use the default value of "name"
                page_offset (int): Page offset. [optional] if omitted the server will use the default value of 0
                page_limit (int): Max number of items. [optional] if omitted the server will use the default value of 10
                sort (str): Sort order. [optional] if omitted the server will use the default value of "name,id"
                filter_name (str): name attribute filter (csv). [optional]
                filter_id (str): id attribute filter (csv). [optional]
                filter (str): Custom Conversation filter. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationColl1
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.get_conversations = _Endpoint(
            settings={
                'response_type': (ConversationColl1,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/',
                'operation_id': 'retrieveacollectionof_conversationobjects0',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'content_type',
                    'include',
                    'fields_conversation',
                    'page_offset',
                    'page_limit',
                    'sort',
                    'filter_name',
                    'filter_id',
                    'filter',
                ],
                'required': [
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                    'content_type',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('content_type',): {

                        "VND.API+JSON": "application/vnd.api+json",
                        "JSON": "application/json"
                    },
                },
                'openapi_types': {
                    'content_type':
                        (str,),
                    'include':
                        (str,),
                    'fields_conversation':
                        (str,),
                    'page_offset':
                        (int,),
                    'page_limit':
                        (int,),
                    'sort':
                        (str,),
                    'filter_name':
                        (str,),
                    'filter_id':
                        (str,),
                    'filter':
                        (str,),
                },
                'attribute_map': {
                    'content_type': 'Content-Type',
                    'include': 'include',
                    'fields_conversation': 'fields[Conversation]',
                    'page_offset': 'page[offset]',
                    'page_limit': 'page[limit]',
                    'sort': 'sort',
                    'filter_name': 'filter[name]',
                    'filter_id': 'filter[id]',
                    'filter': 'filter',
                },
                'location_map': {
                    'content_type': 'header',
                    'include': 'query',
                    'fields_conversation': 'query',
                    'page_offset': 'query',
                    'page_limit': 'query',
                    'sort': 'query',
                    'filter_name': 'query',
                    'filter_id': 'query',
                    'filter': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/vnd.api+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__retrieveacollectionof_conversationobjects0
        )

        def __retrieve_membershipfrommemberships1(
            self,
            conversation_id="531f31a7-5f11-44ae-8d26-9aa0e033181d",
            **kwargs
        ):
            """Retrieve Membership from memberships  # noqa: E501

            Retrieve Membership items from the Conversation memberships \"to-many\" relationship  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_memberships(conversation_id="531f31a7-5f11-44ae-8d26-9aa0e033181d", async_req=True)
            >>> result = thread.get()

            Args:
                conversation_id (str): Conversation item. defaults to "531f31a7-5f11-44ae-8d26-9aa0e033181d", must be one of ["531f31a7-5f11-44ae-8d26-9aa0e033181d"]

            Keyword Args:
                include (str): Membership relationships to include (csv). [optional]
                fields_membership (str): Membership fields to include (csv). [optional] if omitted the server will use the default value of "last_download,user_id,conversation_id,not_read_messages"
                page_offset (int): Page offset. [optional] if omitted the server will use the default value of 0
                page_limit (int): Max number of items. [optional] if omitted the server will use the default value of 10
                sort (str): Sort order. [optional] if omitted the server will use the default value of "last_download,user_id,conversation_id,not_read_messages,id"
                filter_last_download (str): last_download attribute filter (csv). [optional]
                filter_user_id (str): user_id attribute filter (csv). [optional]
                filter_conversation_id (str): conversation_id attribute filter (csv). [optional]
                filter_not_read_messages (str): not_read_messages attribute filter (csv). [optional]
                filter_id (str): id attribute filter (csv). [optional]
                filter (str): Custom Membership filter. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ConversationMembershipsRelColl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['conversation_id'] = \
                conversation_id
            return self.call_with_http_info(**kwargs)

        self.get_memberships = _Endpoint(
            settings={
                'response_type': (ConversationMembershipsRelColl,),
                'auth': [
                    'BasicAuth'
                ],
                'endpoint_path': '/Conversations/{ConversationId}/memberships',
                'operation_id': 'retrieve_membershipfrommemberships1',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'conversation_id',
                    'include',
                    'fields_membership',
                    'page_offset',
                    'page_limit',
                    'sort',
                    'filter_last_download',
                    'filter_user_id',
                    'filter_conversation_id',
                    'filter_not_read_messages',
                    'filter_id',
                    'filter',
                ],
                'required': [
                    'conversation_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'conversation_id':
                        (str,),
                    'include':
                        (str,),
                    'fields_membership':
                        (str,),
                    'page_offset':
                        (int,),
                    'page_limit':
                        (int,),
                    'sort':
                        (str,),
                    'filter_last_download':
                        (str,),
                    'filter_user_id':
                        (str,),
                    'filter_conversation_id':
                        (str,),
                    'filter_not_read_messages':
                        (str,),
                    'filter_id':
                        (str,),
                    'filter':
                        (str,),
                },
                'attribute_map': {
                    'conversation_id': 'ConversationId',
                    'include': 'include',
                    'fields_membership': 'fields[Membership]',
                    'page_offset': 'page[offset]',
                    'page_limit': 'page[limit]',
                    'sort': 'sort',
                    'filter_last_download': 'filter[last_download]',
                    'filter_user_id': 'filter[user_id]',
                    'filter_conversation_id': 'filter[conversation_id]',
                    'filter_not_read_messages': 'filter[not_read_messages]',
                    'filter_id': 'filter[id]',
                    'filter': 'filter',
                },
                'location_map': {
                    'conversation_id': 'path',
                    'include': 'query',
                    'fields_membership': 'query',
                    'page_offset': 'query',
                    'page_limit': 'query',
                    'sort': 'query',
                    'filter_last_download': 'query',
                    'filter_user_id': 'query',
                    'filter_conversation_id': 'query',
                    'filter_not_read_messages': 'query',
                    'filter_id': 'query',
                    'filter': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__retrieve_membershipfrommemberships1
        )

