"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user_coll import UserColl


class TestUserColl(unittest.TestCase):
    """UserColl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserColl(self):
        """Test UserColl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserColl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
