"""
    Messages server

    SAFRSAPI  # noqa: E501

    The version of the OpenAPI document: 0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.jsonapi_error403 import JsonapiError403


class TestJsonapiError403(unittest.TestCase):
    """JsonapiError403 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonapiError403(self):
        """Test JsonapiError403"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JsonapiError403()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
